spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center
    username: root
    password: 123456

  application:
    # 服务名称尽量使用-,不要使用_,不要用特殊字符
    name: user-center

  cloud:
    nacos:
      discovery:
        #指定nacos server的地址
        server-addr: localhost:8848
        # 指定namespace
        # namespace: 79b188a4-b5b3-45d6-9987-9bd278e94d04
        # NJ
        # 指定集群名称
        # cluster-name: NJ
        # 元数据
        metadata:
          instance: c
          haha: hehe
          version: v1

